
---

apiVersion: apps/v1
kind: Service
metadata: 
  name: nginx-svc
  namespace: default

spec: 
  ports: 
  - nodePort: 30001 #range is 30000- 
    port: 80


    targetPort: 80

  selector: 
    app: nginx # this label connects this service to deployment

  type: NodePort