
---

apiVersion: v1
kind: Service
metadata: 
  name: nodejs-app-svc
  namespace: default

spec: 
  ports: 
  - nodePort: 30002 #range is 30000- 
    port: 3000


    targetPort: 3000

  selector: 
    app: nodejs-app # this label connects this service to deployment

  type: NodePort